django_blog/urls.py
from django.contrib import admin
from django.urls import path
from Blog import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('post/<int:pk>/',views.PostDetailView.as_view(), name='post-detail'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('news/', views.PostListView.as_view(), name='news'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('sign-in', auth_views.LoginView.as_view(template_name='Blog/login.html'), name='sign-in'),
]

Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver


# Create your models here.


class Blog(models.Model):

    user = models.OneToOneField(User, models.CASCADE, unique=True, related_name='blog')
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog-detail', kwargs={'pk': self.pk})

class Post(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='post')
    title = models.CharField(max_length=100)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-pub_date', )


    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('post-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    
class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscription')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='subscription')

    class Meta:
        unique_together = ('user', 'blog')


class MarkedAsRead(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='marked')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='marked')

    class Meta:
        unique_together = ('user', 'post')

@receiver(post_save, sender=User)
def save_blog(sender, instance, created, **kwargs):
    if created:
        name = "{}s Blog".format(instance.get_username())
        Blog.objects.create(user=instance, name=name)

@receiver(pre_delete, sender=Subscription)
def delete_marks(sender, instance, **kwargs):
    blogs_posts = Post.objects.filter(blog=instance.blog)
    MarkedAsRead.objects.filter(user=instance.user, post__in=blogs_posts).delete()

Blog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Blog, Post, Subscription, MarkedAsRead
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from django.contrib.sites.models import Site
# Create your views here.

@receiver(post_save, sender=Post)
def send_notification(sender, instance, **kwargs):
    recipient_list = Subscription.objects.filter(blog=instance.blog).exclude(user__email='')
    if recipient_list.exists():
        recipient_list = recipient_list.values_list('user__email', flat=True)
        subject = 'New post'
        domain = Site.objects.get_current().domain
        print(domain)
        post_url = "http://{0}:8000{1}".format(domain, instance.get_absolute_url())
        message = render_to_string('email/notification.html', {'blog':instance.blog, 'post_url':post_url})
        send_mail(subject, message=message, from_email='Blog', recipient_list=recipient_list)



class HomeView(generic.ListView):
    model = Blog
    template_name = 'Blog/home.html'

    def get_queryset(self):
        
        if self.request.user.is_authenticated:
            blogs = Blog.objects.exclude(user=self.request.user)
        else:
            blogs = Blog.objects.all()
        return blogs


class BlogDetailView(generic.DetailView):
    model = Blog
    
    def post(self, request, *args, **kwargs):
        blog = self.get_object()
        subscription, created = Subscription.objects.get_or_create(user=request.user, blog=blog)
        if not created:
            subscription.delete()

        return redirect(blog.get_absolute_url())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['subbed'] = Subscription.objects.filter(Q(user=self.request.user) & Q(blog=self.get_object())).exists()
            return context
        except TypeError:
            return context


class PostDetailView(generic.DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('sign-in')
    model = Post
    fields = ('title', 'content', )
    
    def get_success_url(self):
        return self.request.user.blog.get_absolute_url()

    def form_valid(self, form):
        form.instance.blog = self.request.user.blog
        return super().form_valid(form)


class PostListView(LoginRequiredMixin, generic.ListView):
    login_url = reverse_lazy('sign-in')
    model = Post

    def post(self, request, *args, **kwargs):
        post = Post.objects.get(id=request.POST['id'])
        MarkedAsRead.objects.create(user=request.user, post=post)
        return redirect(reverse('news'))

    def get_queryset(self):
        subscribed_blogs = Blog.objects.filter(subscription__user=self.request.user)
        posts = Post.objects.filter(blog__in=subscribed_blogs).exclude(marked__user=self.request.user)
        return posts

Blog/templates/Blog/blog_detail.html
{% extends 'Blog/generic.html' %}



{% block title %}
    <title>Blog</title>
{% endblock title %}
        

{% block content %}
    <h1>{{ blog.name }}</h1>
    <br>
    
    {% if user.is_authenticated %}        

        {% if blog.user == user %}
            <a href="{% url 'post-create' %} ">New post</a>
        {% else %}
            <form action="{% url 'blog-detail' blog.id%}" method="post">
                {% csrf_token %}
                <input type="submit" value="{% if not subbed %}Subscribe{% else %}Unsubscribe{% endif %}">
            </form>
        {% endif %}
    {% endif %}   

    
        {% for post in blog.post.all  %}
            <div class="post-box" style="margin-top:100px">
                <a href="{{ post.get_absolute_url }}"><h3>{{ post.title }}</h3></a>
                <p>{{ post.content }}</p>
                <p>Created: {{ post.pub_date|timesince }} ago</p>
            </div>
        {% endfor %}
  
        
{% endblock content %}
    

Blog/templates/Blog/generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}{% endblock title %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

</head>

<body>

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-2">
                <ul class="sidebar-nav">
                    <li><a href="{% url 'home' %}">All blogs</a></li>
                    <br>
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{{ user.blog.get_absolute_url }}">My Blog</a></li>
                        <li><a href="{% url 'news' %}">News</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'sign-in' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}
                </ul>
                
            </div>
            <div class="col-sm-4 offset-sm-2">
                {% block content %}{% endblock content %}

            </div>

        </div>            
    </div>

</body>
</html>

Blog/templates/Blog/home.html
{% extends 'Blog/generic.html' %}


{% block title %}
    <title>Home</title>
{% endblock title %}
    


{% block content %}
    <h1>Blogs</h1>
    <br>
    <br>
    {% for blog in blog_list %}
        <a href="{{ blog.get_absolute_url }}"><h3>{{ blog.name }}</h3></a>
    {% endfor %}
        

{% endblock content %}
    

Blog/templates/Blog/login.html
{% extends 'Blog/generic.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title>Sign in</title>
{% endblock title %}
    

{% block content %}
    <h1>Sign in</h1>    
    <br>
    <form action="{% url 'sign-in' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Sign in">
    </form>
{% endblock content %}
    

Blog/templates/Blog/post_List.html
{% extends 'Blog/generic.html' %}


{% block title %}
    <title>News</title>
{% endblock title %}


{% block content %}
    <h1>New posts</h1>
    <br>
    {% for post in post_list %}
    <div class="post-box" style="margin-top:100px">
        <a href="{{ post.get_absolute_url }}"><h3>{{ post.title }}</h3></a>
        <p>{{ post.content }}</p>
        <a href="{% url 'blog-detail' post.blog.id %}">{{ post.blog }}</a>
        <p>Created: {{ post.pub_date|timesince }} ago</p>
        <form action="{% url 'news' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ post.id }}">
            <input type="submit" value="Mark as read">
        </form>
    </div>
    {% endfor %}
        

{% endblock content %}
    

Blog/templates/Blog/post_detail.html
{% extends 'Blog/generic.html' %}



{% block title %}
    <title>Post</title>
{% endblock title %}


{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <a href="{{ post.blog.get_absolute_url }}">{{ post.blog }}</a>
    <p>Created: {{ post.pub_date|timesince }} ago</p>
{% endblock content %}
    
    

Blog/templates/Blog/post_form.html
{% extends 'Blog/generic.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Post Create</title>
{% endblock title %}
    

{% block content %}
    <h1>New post</h1>

    <form action="{% url 'post-create' %}" method="POST" >
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Create">
    </form>
{% endblock content %}
    